version: '3.1'

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=%BUNDLENAME%-user
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=%BUNDLENAME%-db
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  postgresql:
    driver: local
